[package]
name = "hustnet-keepalive"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.*", features = ["blocking"] }
regex = "1.10.*"
url = "2.5.*"
crypto-bigint = "0.5.*"
